from tkinter import *
root=Tk()
v= StringVar()
v.set(1)
frame=Frame(root)
label1= Label(root,text="Name")
label1.pack(padx=15,pady=5)
entry1=Entry(root,bd=5)
entry1.pack(padx=15,pady=5)
label2=Label(root,text="Roll No")
label2.pack(padx=15,pady=6)
entry2=Entry(root,bd=5)
entry2.pack(padx=15,pady=6)
label3=Label(root,text="Reg.No")
label3.pack(padx=15,pady=7)
entry3=Entry(root,bd=5)
entry3.pack(padx=15,pady=7)
bn1=Button(frame,text="Submit",command=btn1)
bn1.pack(side=RIGHT,padx=5)
frame.pack()
root.mainloop()